# Generated by Django 2.1.4 on 2019-10-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191012_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcategory',
            name='image',
            field=models.CharField(default='for image', max_length=20),
        ),
    ]
