# Generated by Django 2.1.4 on 2019-10-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tutorialcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='tutorialseries',
            name='image',
            field=models.CharField(default='for image', max_length=20),
        ),
    ]
