# Generated by Django 2.1.4 on 2019-10-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191020_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='image',
            new_name='image_ser',
        ),
        migrations.AddField(
            model_name='tutorialcategory',
            name='image_cat',
            field=models.CharField(default='for image', max_length=20),
        ),
    ]
