# Generated by Django 3.1.3 on 2021-01-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191020_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialcategory',
            name='image_cat',
        ),
        migrations.RemoveField(
            model_name='tutorialseries',
            name='image_ser',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='page_title',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='tutorialcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='tutorialseries',
            name='images',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
